### ISSUE TITLE
数据库字段名与java字段名映射的驼峰下划线转换有问题

### ISSUE THREAD

**Issue by liguangyulgy** [liukefeng2008/idea-plugin-jpa-support#17]
如果字段名是大写带下划线，例如“REC_ID”，则现在转换出的java字段名为rECID

**Comment by liukefeng2008** [comment]
嗯，这种情况确实不好处理，如果一个字段名是 `foo_ID`，可能期望的变量名称是`fooID`，粗暴转换为`fooId`也不太好

**Comment by honeykee** [comment]
按照大多数的习惯来可以减少修改。希望可以调整一下，感谢大佬
