### ISSUE TITLE
数据库字段驼峰命名法命名会有问题

### ISSUE THREAD

**Issue by tang1998bjt** [liukefeng2008/idea-plugin-jpa-support#20]
![image](https://user-images.githubusercontent.com/33611020/60476084-c8484c00-9cac-11e9-999a-28ccdfc5b07d.png)
生成的column也会驼峰命名,导致JPA自动转下划线找不到该字段

**Comment by liukefeng2008** [comment]
请提供可以用于测的`DDL`

**Comment by liukefeng2008** [comment]
[Jpa Support-1.1.2.zip](https://github.com/liukefeng2008/idea-plugin-jpa-support/files/3355548/Jpa.Support-1.1.2.zip)

这是最新的版本，看看能不能解决问题
