### ISSUE TITLE
jpa 2.2支持java8时间格式

### ISSUE THREAD

**Issue by litttlefisher** [liukefeng2008/idea-plugin-jpa-support#24]
jpa2.2里面，已经支持了java8中的例如LocalDateTime、LocalDate、LocalTime作为字段类型了。是否可以在Prefererce里面增加一个配置面板来决定时间类型的默认类型是Date还是LocalDateTime什么的

**Comment by liukefeng2008** [comment]
good idea

**Comment by liukefeng2008** [comment]
你好，已经支持，请更新成新版本
