### ISSUE TITLE
数据库版本问题

### ISSUE THREAD

**Issue by isyihao** [liukefeng2008/idea-plugin-jpa-support#25]
貌似只支持数据库5.x和6.x的版本?我测试数据库8.x版本都是连接失败
Error: 连接数据库失败 (1193,HY000,Unknown system variable 'query_cache_size') (moments ago)

**Comment by liukefeng2008** [comment]
[该版本支持`8.x`](https://github.com/liukefeng2008/idea-plugin-jpa-support/issues/19#issuecomment-508131691)

新版本暂时未发布到 Idea plugin repository，可以通过本地安装的方式更新
