### ISSUE TITLE
第一次连接数据库时，能否指定本地的mysql驱动

### ISSUE THREAD

**Issue by hchaojie** [liukefeng2008/idea-plugin-jpa-support#28]
设置数据库连接界面，选择不同驱动的时候，会自动去maven仓库下载数据库驱动，这一步时间比较长，并且ui界面会卡住。一般开发者本地maven仓库都有相关驱动，能否添加一个选项，可以指定本地驱动？

**Comment by liukefeng2008** [comment]
也许使用国内的maven镜像在一定程度上能够缓解这个问题，而且也减少操作成本
