### ISSUE TITLE
添加选项，可以选择4个空格的缩进或者2个空格

### ISSUE THREAD

**Issue by hchaojie** [liukefeng2008/idea-plugin-jpa-support#29]
看了一下代码，有提供了4个空格，2个空格和 tab的选项，但是目前似乎代码里面写死了2个空格，应该很容易添加一个界面选项的。
感谢作者开发的工具，代码逻辑很清楚，可能没时间完善吧。

**Comment by liukefeng2008** [comment]
下一个版本加上该功能
