### ISSUE TITLE
Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by lazerta** [liukefeng2008/idea-plugin-jpa-support#35]
`9:31 PM	Error: Unable to connect to the database. (1193,HY000,Unknown system variable 'query_cache_size')
`

unable to connect database

**Comment by liukefeng2008** [comment]
![image](https://user-images.githubusercontent.com/18641671/67675239-9d030e80-f9b9-11e9-84b3-fb03436f0a90.png)

You can click 'Switch database' to get a compatible driver.

**Comment by lazerta** [comment]
How to add compatible driver to plugin?
