### ISSUE TITLE
![image](https://user-images.githubusercontent.com/18641671/67675239-9d030e80-f9b9-11e9-84b3-fb03436f0a90.png)

### ISSUE THREAD

**Issue by lazerta** [liukefeng2008/idea-plugin-jpa-support#36]
![image](https://user-images.githubusercontent.com/18641671/67675239-9d030e80-f9b9-11e9-84b3-fb03436f0a90.png)

You can click 'Switch database' to get a compatible driver.

_Originally posted by @liukefeng2008 in https://github.com/liukefeng2008/idea-plugin-jpa-support/issues/35#issuecomment-546906492_

How to add compatible driver to plugin?

**Comment by liukefeng2008** [comment]
The latest version of the plugin contains these drivers.

**Comment by lazerta** [comment]
Not compatible with 

IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 amd64

**Comment by lazerta** [comment]
@liukefeng2008

**Comment by liukefeng2008** [comment]
On, sorry, current version not support `JDK9+`.
If you want to use it in the `IntelliJ IDEA 2019.2.3`, You should follow the steps below:
1. Click menu`Help -> Find Action...`
![image](https://user-images.githubusercontent.com/18641671/67739649-2401c680-fa4e-11e9-8268-f4fe4f2fac51.png)
2. Input`Switch Boot JDK`
![image](https://user-images.githubusercontent.com/18641671/67739688-43005880-fa4e-11e9-87d2-d9fd78918054.png)
3. Choose `JDK 1.8`
![image](https://user-images.githubusercontent.com/18641671/67739718-5ca1a000-fa4e-11e9-9d7e-dc147a4bb5dd.png)
4. Restart `IDEA`
5. Use `Jpa Support` to generate `Entity`

**Comment by lazerta** [comment]
@liukefeng2008 
Thank you for your help.
It still says incompatible version for the latest version, despite I switched boot jdk
`AdoptOpenJDK\openjdk-8u232-b09`

**Comment by liukefeng2008** [comment]
@lazerta  你可以下载最新版本 [1.1.5](https://plugins.jetbrains.com/plugin/10707-jpa-support/versions)，该版本支持JDK9+

**Comment by liukefeng2008** [comment]
@lazerta The latest version has fixed this bug.[1.1.6](https://plugins.jetbrains.com/plugin/10707-jpa-support/update/76105)
