### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by JackCreativeCrew** [liukefeng2008/idea-plugin-jpa-support#37]
I get an exception trying to run this on windows because of the path separators:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: separators must be '/'; path is C:\Program Files\JetBrains\IntelliJ IDEA 2019.2\jbr\bin\driver_vendor
at com.intellij.ide.util.DirectoryUtil.mkdirs(DirectoryUtil.java:31)
at com.ifengxue.plugin.JpaSupport$DownloadDriverRunnable.lambda$run$1(JpaSupport.java:429)
```

This occurred downloading the driver for PostgreSQL 42.2.5 after clicking download driver in the modal window.
![image](https://user-images.githubusercontent.com/49384070/69019613-727b0300-0a05-11ea-843b-e097e40b2da6.png)

**Comment by liukefeng2008** [comment]
You shuold upgrade the version to latest.
