### ISSUE TITLE
生成的entity，默认值的问题。

### ISSUE THREAD

**Issue by onlylxz** [liukefeng2008/idea-plugin-jpa-support#39]
当数据库指定字段默认值时，生成的实体类会自动赋值为指定的默认值，如图
![image](https://user-images.githubusercontent.com/22471577/69301374-12789c80-0c51-11ea-8c38-cee837ec779f.png)
这样查询的时候会带入这个默认值。这个可以在生成的时候不对属性赋值吗？

**Comment by liukefeng2008** [comment]
1.个人不太建议建表时填一些较为不正规的默认值
2.个人不太建议查询时直接使用实体来做为查询条件的容器，可以使用`QueryDSL JPA`，或者接口继承`JpaSpecificationExecutor`
3. 不使用默认值这个需求我再观察下

**Comment by onlylxz** [comment]
好的，建议中肯，感谢答复
