### ISSUE TITLE
Can not connect to postgresql

### ISSUE THREAD

**Issue by chenjienn** [liukefeng2008/idea-plugin-jpa-support#40]
![image](https://user-images.githubusercontent.com/13412289/71469640-cfd45200-2804-11ea-8c15-0fb3807551db.png)

always remind me this issue
idea version is 2019.3.1

**Comment by liukefeng2008** [comment]
你可以尝试查看该目录下是否有对应的驱动
https://github.com/liukefeng2008/idea-plugin-jpa-support/blob/923638ad9ebc5c7609fdfb54ad7ad0d01e0c7827/src/main/java/com/ifengxue/plugin/JpaSupport.java#L434
