### ISSUE TITLE
生成的entity是否可以加上前缀和后缀？

### ISSUE THREAD

**Issue by walnut-tom** [liukefeng2008/idea-plugin-jpa-support#42]
比如：
table_name: user
现在生成为 User
是否可以增加配置生成为 PrefixUserEntity, 其中 Prefix 和 Entity 可配置
谢谢

**Comment by liukefeng2008** [comment]
非常好的建议，下个版本加上

**Comment by liukefeng2008** [comment]
最新版本已经支持[1.1.6](https://plugins.jetbrains.com/plugin/10707-jpa-support/update/76105)
