### ISSUE TITLE
切换mysql驱动的问题

### ISSUE THREAD

**Issue by ixiongyu** [liukefeng2008/idea-plugin-jpa-support#43]
貌似更换驱动版本好像有点问题，我选择了8.0.16，但是还是会报Unknown system variable 'query_cache_size'这个错误。

**Comment by ixiongyu** [comment]
<img width="746" alt="QQ20200118-230245@2x" src="https://user-images.githubusercontent.com/11729558/72665804-dc844880-3a46-11ea-9f20-d1fb29374741.png">
<img width="280" alt="QQ20200118-230441@2x" src="https://user-images.githubusercontent.com/11729558/72665811-ee65eb80-3a46-11ea-9d5e-435f96c4e410.png">

**Comment by liukefeng2008** [comment]
@ixiongyu  你现在用的plugin版本号是多少？

**Comment by ixiongyu** [comment]
插件是1.1.5
idea 是2019.3.1
操作系统是 macOs 10.15.2

**Comment by liukefeng2008** [comment]
好的，该问题已复现，修复后在这里回复

**Comment by liukefeng2008** [comment]
最新版已修复次bug.[1.1.6](https://plugins.jetbrains.com/plugin/10707-jpa-support/update/76105)
