### ISSUE TITLE
Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by gth56** [liukefeng2008/idea-plugin-jpa-support#44]
Got this error on connect to mysql 8.0.16

**Comment by liukefeng2008** [comment]
This issue is known, please wait for a fixed version

**Comment by gth56** [comment]
Thanks for the feedback.

Gesendet mit der WEB.DE Mail App

Am 20.01.20 um 07:53 schrieb liukefeng2008

**Comment by liukefeng2008** [comment]
The latest version has fixed this bug.[1.1.6](https://plugins.jetbrains.com/plugin/10707-jpa-support/update/76105)
