### ISSUE TITLE
数据库版本有要求吗？

### ISSUE THREAD

**Issue by dlyong** [liukefeng2008/idea-plugin-jpa-support#6]
总也是连接不上数据库

**Comment by liukefeng2008** [comment]
你当前的数据库版本是多少呢？，如果连接不上数据库会有报错信息的，右下角的`Event Log`

**Comment by dlyong** [comment]
我当前数据库的版本是5.1.71-community；
异常是连接数据库失败java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
我降低了这个连接mysql驱动器版本，还是不好用，我现在驱动器版本是5.1.34

**Comment by dlyong** [comment]
![image](https://user-images.githubusercontent.com/40163649/55450763-d8e01c00-5602-11e9-802f-83a70437f3bb.png)

**Comment by engineer-myoa** [comment]
This is same issue with #7.
https://github.com/liukefeng2008/idea-plugin-jpa-support/issues/7
Make sure hopeful :)

**Comment by liukefeng2008** [comment]
> 我当前数据库的版本是5.1.71-community；
> 异常是连接数据库失败java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
> 我降低了这个连接mysql驱动器版本，还是不好用，我现在驱动器版本是5.1.34

应该是插件使用的`driver`版本比数据库的版本高导致的，我会在下个版本支持使用自定义的`driver`
