### ISSUE TITLE
连接mariadb的时候提示报错，需要加入?serverTimezone=UTC,能否设置动态配置连接url

### ISSUE THREAD

**Issue by hu582205** [liukefeng2008/idea-plugin-jpa-support#7]
连接mariadb的时候提示报错，需要加入?serverTimezone=UTC,能否设置动态配置连接url
错误信息：
You must configure either the server or JDBC driver (via the serverTimezone configuration property)

**Comment by engineer-myoa** [comment]
If you need add parameters, Temporarily, you can add parameter in database input box.
like this.
dbname?serverTimezone=UTC

Please referred url below :)
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-jdbc-url-format.html

**Comment by liukefeng2008** [comment]
Maybe add parameter to database input box can not work.
```
String url =
          "jdbc:mysql://" + host + ":" + port + "/" + database + "?useUnicode=true&charset=utf8";
```

I will add new input box for connection url and allow user use custom driver.

**Comment by hu582205** [comment]
thanks

**Comment by engineer-myoa** [comment]
> Maybe add parameter to database input box can not work.
> 
> ```
> String url =
>           "jdbc:mysql://" + host + ":" + port + "/" + database + "?useUnicode=true&charset=utf8";
> ```
> I will add new input box for connection url and allow user use custom driver.

You are right. It change to accept custom parameter :)
(In my case has same issue in my forked repository, So it applied but forgotten it T T)
